# Generated by Django 5.0.6 on 2024-11-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playera',
            name='color_personalizado',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='playera',
            name='nombre_personalizado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='playera',
            name='numero_personalizado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
