# Generated by Django 5.0.6 on 2024-11-15 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_playera_escudo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playera',
            name='color_personalizado',
        ),
        migrations.RemoveField(
            model_name='playera',
            name='escudo',
        ),
        migrations.RemoveField(
            model_name='playera',
            name='nombre_personalizado',
        ),
        migrations.RemoveField(
            model_name='playera',
            name='numero_personalizado',
        ),
        migrations.CreateModel(
            name='PlayeraPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_personalizado', models.CharField(max_length=100)),
                ('numero_personalizado', models.IntegerField()),
                ('color_personalizado', models.CharField(max_length=7)),
                ('escudo', models.ImageField(blank=True, null=True, upload_to='escudos/')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('playera_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalizaciones', to='productos.playera')),
            ],
        ),
    ]
