# Generated by Django 5.0.6 on 2024-11-15 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_playera_color_personalizado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerapersonalizada',
            name='precio',
        ),
    ]
