# Generated by Django 5.0.6 on 2024-11-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_playerapersonalizada_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerapersonalizada',
            name='precio',
        ),
        migrations.AddField(
            model_name='playera',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='playerapersonalizada',
            name='color_personalizado',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
