# Generated by Django 5.0.6 on 2024-11-18 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_remove_playerapersonalizada_precio_playera_activo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='En espera', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('personalizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.playerapersonalizada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
